### ISSUE TITLE
A Ruby Text or hardcopy Recommendation?

### ISSUE THREAD

**Issue by mrarthurwhite** [learn-co-curriculum/programming-univbasics-the-variable-lookup-expression#4]
Is there a ruby book that people recommend as a reference or go to guide when going through the Software Engineering course?

I used some ebooks prior for an ROR project but that was a while back. 
I prefer books for offline access (no internet connection) in conjunction with an ebook (for search/reference).

**Comment by maxwellbenton** [comment]
Hi @mrarthurwhite,

Some of our materials include resource links to one book that is pretty comprehensive that is free online: http://ruby.bastardsbook.com/

That site also includes a good list of recommended readings for Ruby: http://ruby.bastardsbook.com/resources/

Hope this helps!
